name: Docker Image CI

on:
  push:
    branches: [ "an/assessment" ]

env:
  PORT_ARG: 80

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag alexenelson/quest:latest --build-arg PORT_ARG=$PORT_ARG .
    - name: Docker push
      run: docker push alexenelson/quest:latest
