name: Docker Image CI

on:
  push:
    branches: [ "an/assessment" ]

env:
  PORT_ARG: 80
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag alexenelson/quest:latest --build-arg PORT_ARG=$PORT_ARG .
    - name: Docker push
      run: docker push alexenelson/quest:latest
    - name: CDK Deploy
      run: cd quest-deploy && npm i && npm run cdk deploy