name: Docker Image CI

on:
  push:
    branches: [ "master", "an/secret-parameter" ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  TAG: ${{ github.run_number }}
  MY_GITHUB_SECRET: ${{ github.MY_GITHUB_SECRET }}

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag alexenelson/quest:$TAG .
    - name: Docker push
      run: docker push alexenelson/quest:$TAG
    - name: CDK Deploy
      run: cd quest-deploy && npm i && npx cdk deploy --require-approval never -c TAG=$TAG -c SECRET_WORD=$MY_GITHUB_SECRET